package.json, src/components/Menu.jsx
*resolve issue:* #47
Tested using NVDIA Screen Reader Accessibility Device.
=> improved button accessability

README.md
*resolve issue:* #30 
Checked locally and on github
=> [docs]: Added a section titled, 'Using Drawing Tools' as per requirement

index.html
*resolve issue:* #46 
Testing using Google Lighthouse.
=> improve seo by adding important meta tags

src/utils/canvas.js
*resolve issue:* #64
"I tested the changes on my mobile device to ensure stability while drawing on the whiteboard UI. I verified that the drawing functionality behaves as expected and that the user interface remains stable during drawing interactions. Additionally, I ensured that the scrolling issue reported in the previous version is resolved and that no new issues were introduced.
https://github.com/singodiyashubham87/Draw-it-out/assets/146753809/8be435c8-cf90-4da0-9614-99de582de34f
=>       fixed the [BUG] Unstable UI on mobile devices while drawing on white board #64

src/App.jsx
*resolve issue:*  #76 
I have changed the parent div to w-[full] ie width:100%. now it does not got beyond the screen
=> closes Issue #76

README.md, src/App.jsx, src/components/Menu.jsx, src/utils/canvas.js
*resolve issue:* #37
Tested it manually multiple times. And documentation changes also done.
=> [FEAT] Resizeable Board #37

package-lock.json, package.json, src/components/Menu.jsx, src/utils/canvas.js
*resolve issue:* #34 
I have used jsPdf library to export the canvas to PDF. 
https://github.com/singodiyashubham87/Draw-it-out/assets/91741581/c2ac3233-edac-49de-a6f7-8cef8b635089
=> feat: Export to PDF and SVG

src/App.jsx
*resolve issue:*  Ref- #70 
Fixes:
@singodiyashubham87 
This is in reference to #70 . Please check it
=> Ref: #70  [Added a "Buy me a coffee" button]

src/App.jsx
custom canvas background color picker
*resolve issue:* custom canvas background color picker #61
=> rainbow background color"

src/components/BgColor.jsx
*resolve issue:* #42
Tested it manually on my local setup
=> [feat]:hover-on-color-icons

src/App.jsx, src/index.css
#107 
- In this project was `Responsive` error fixes..
=> [Bug] : Responsive Fixes

src/App.jsx, src/components/Menu.jsx, src/utils/canvas.js
*resolve issue:* #2
https://github.com/singodiyashubham87/Draw-it-out/assets/122858524/fa453aa6-b66d-46ac-9c40-2a7e203f64ad
=> Fixed #2: Resolved the issue of screen getting cleared on changing the pen stroke or color

package-lock.json, package.json, src/App.jsx, src/components/Menu.jsx
[FEAT] Add a animated Onboarding tour of website. #101
Added a Quick Walkthrough to our website using react-royride
Feature
=> Added a Walk Through

.github/workflows/greetings.yaml
Added Workflow For automated comments #98
=> Create greetings.yaml #98

src/App.jsx
*resolves issue:* #130 
tested using the responsive developer tool in firefox 
https://github.com/singodiyashubham87/Draw-it-out/assets/32983571/67c97091-3e0c-4617-9289-b20f3e212550
=> fixed the breakpoint issue on tablets 

package-lock.json, package.json, src/App.jsx
*resolve issue:* #158 
I have checked the deployment in my localhost server
=> Fixed the button

src/App.jsx, src/components/DrawingShapes.jsx, src/components/Menu.jsx
*resolve issue:* #166 
https://github.com/singodiyashubham87/Draw-it-out/assets/123164129/75057b44-c0bd-4ed2-8918-a7ba503b2778
=> closes issue #166

src/App.jsx
*resolve issue:* #161 
checked with localhost server
=> [BUG] : Multiple bot options instead of one #161fix: duplicate chatbot

package-lock.json, package.json, src/App.jsx, src/utils/helpers.js
Refactored App.jsx by shifting tourSteps to utils.js
=> [REFACTOR] tourSteps

src/App.jsx
*resolve issue:* #168 
* Users now don't have to scroll down to access the canvas fully. The alignment is adjusted without modifying the height of the canvas. ( Altered the unnecessary container height ).
* However , users still have to scroll down to access the "clearAll" button and the complete color palette box. Not covering those issues as it was not assigned. 
* However Iam interested to fix those too either by using this same pull request or by creating a new issue. (Please let me know)
=> fixed the scroll issue

README.md
*resolve issue:* #171
I have corrected the sentence and added description of shapes.
Example of how to mark a checkbox:-
My code follows the code style of this project.
My code follows the guidelines of this project.
I have performed a self-review of my own code.
I have commented my code, particularly wherever it was hard to understand.
I have made corresponding changes to the documentation.
My changes generate no new warnings.
I have added things that prove my fix is effective or that my feature works.
Any dependent changes have been merged and published in downstream modules.
=> Update README(issue 171).md

src/App.jsx, tailwind.config.js
*resolve issue:* #207 
I have fixed the CSS of the guidelines box so that the text is clearly visible in both light and dark mode.
I have run the code and here are the screenshots of the changes: 
Light Mode(No change):
Dark Mode(changed):
=> Guidelines visibility in dark mode (Fix Issue #207)

src/App.jsx, src/components/Menu.jsx
=> Fixed #137:Resolving pen stroke feature

.eslintrc.cjs, src/components/BgColorSidePanel.jsx, src/components/DrawingShapes.jsx, src/components/Footer.jsx, src/components/Menu.jsx, src/utils/canvas.js
*resolve issue:* #230 
I have made minor changes in the code such as formatting, commenting out code, applying Prettier, ESLint
I have run the application locally using `npm run dev` and it seems fine to me.
Let me know if I need to make any additional changes. Thanks:)
=> chore: Disable prop-types rule in ESLint configuration, cleanup code

src/utils/helpers.js
*resolve issue:* #220
- Joyride placement for the color pallet step was causing improper scroll behaviour
- I have fixed it by changing it's placement to right
- I have tested it in my local environment and it is working fine now
=> fix: improper scrolling behaviour by changing joyride placement

src/components/Chatbot/Chatbot.jsx
*resolves issue:* #273
- [x ] Code style update (formatting, local variables)
- [x ] My code follows the guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly wherever it was hard to understand.
- [x ] I have made corresponding changes to the documentation.
- [x ] My changes generate no new warnings.
- [x ] I have added things that prove my fix is effective or that my feature works.
- [x ] Any dependent changes have been merged and published in downstream modules.
=>  components/chatbot: change font color for 'End Chat'

README.md
*resolve issue:* #249 
```
<table align="center">
<thead align="center">
<tr border: 1px;>
<td><b><img src="https://raw.githubusercontent.com/Tarikul-Islam-Anik/tarikul-islam-anik/main/assets/images/Star.png" width="20" height="20"> Stars</b></td>
<td><b>🍴 Forks</b></td>
<td><b><img src="https://raw.githubusercontent.com/Tarikul-Islam-Anik/tarikul-islam-anik/main/assets/images/Lady%20Beetle.png" width="20" height="20"> Issues</b></td>
<td><b><img src="https://raw.githubusercontent.com/Tarikul-Islam-Anik/tarikul-islam-anik/main/assets/images/Check%20Mark%20Button.png" width="20" height="20"> Open PRs</b></td>
<td><b><img src="https://raw.githubusercontent.com/Tarikul-Islam-Anik/tarikul-islam-anik/main/assets/images/Cross%20Mark.png" width="20" …
```
=> [DOCS] Addition of no of forks star issue closed open pr to readme.md

.github/pull_request_template.md
*resolve issue:* #issue_number
=> chore: update PR template to link issues with PRs automatically

src/index.css
*closes* #issue_number #334
**If it's not good, please assign me again I will do it better**
=> [Feature Request]: Style added to Scrollbar

src/components/Footer.jsx
Hello Project Admin 
I Added Icons - Solved #386  
Kindly Please go through it @0xabdulkhalid
=> Added Icons

src/components/Footer.jsx
*closes* #390 
- [x ] My code follows the guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly wherever it was hard to understand.
- [x ] I have made corresponding changes to the documentation.
- [x ] My changes generate no new warnings.
- [x ] I have added things that prove my fix is effective or that my feature works.
- [x ] Any dependent changes have been merged and published in downstream modules.
=> Made changes in the footer

src/utils/canvas.js
*closes* #303 
I have tested pen functionality on my laptop (which has a touchscreen as well) using the following browsers: 
- Microsoft Edge
- Google Chrome
- Mozilla Firefox
- Opera GX
- Brave
The pen works perfectly in all these browsers without any misalignment. I haven't tested it on a smartphone, though.
=> Fix pen alignment issues for both mouse and touch (#303)

src/components/Chatbot/Chatbot.jsx
*closes* #253 
The changes are tested locally by running the application and verifying the alignment of the chatbot and Gmail icons in the footer. Both icons are now visible and properly spaced out, resolving the overlap issue. Testing is also performed across different screen sizes and resolutions to ensure the fix works as expected.
Screenshots-
Before:
After:
=> fix(footer): chatbot alignment adjusted

src/components/Footer.jsx
[BUG] : Resposive Missing
*closes* #201 
[Screencast from 2024-06-26 12-37-52.webm](https://github.com/singodiyashubham87/Draw-it-out/assets/121082414/f75f6e65-c053-4082-93d8-323d552a8f59)
[Screencast from 2024-06-26 12-38-33.webm](https://github.com/singodiyashubham87/Draw-it-out/assets/121082414/af9af2f9-df0b-4d23-a11b-28b089eba396)
=> [BUG] : Resposive Missing

src/components/DrawingShapes.jsx
*closes* #373 
Added the individual hover effect on shape selection
=> Added individual hover effect on shapes

src/components/Menu.jsx
*closes* #189 
Tested by running in the local server
=> Fixed the pen dropdown visiblity in dark mode

src/components/DrawingShapes.jsx
=> Added the auto dropdown close feature

.github/workflows/codeql.yml
Closes: #413  
- `.github/workflows/codeql.yml`
1. **Go to your project repository settings**
2. **On left pane > Actions > General**
3. **Scroll down and Go to Workflow permissions > select "Read and write permissions"**
4. **Click save and its done.**
@singodiyashubham87 Please review this PR. After merging the PR, don't forget to add `gssoc24` ,`level` labels and assign this PR to me, otherwise my points won't be added.
Thanks
=> feat: add codeql ci/cd workflow for javascript

src/App.jsx, src/components/Menu.jsx, src/utils/helpers.js
*closes* #423 
- Added elements that highlight different components of the app to give insight to the user
- Fixed the previous tour elements that were not working. 
This video displays the changes I have made and how they look like now:-
https://github.com/singodiyashubham87/Draw-it-out/assets/92578876/fad0e33c-8529-4266-a85f-ea8e26151f4e
The changes have been verified and tested on my local machine.
Additionally, I would request you to please consider re-evaluating the level of this issue since I had to go through the whole code-base and read almost every single line to find the elements that need to be highlighted.
=> Fixed the start tour/tutorial

src/App.jsx
Icon not visible in dark mode #236
=> Buy me coffee icon visible in dark mode

src/App.jsx
Hey @singodiyashubham87 issue closes #427 
I have made the website Canvas Responsive.
=>  Made The Website "Canvas Responsive"

src/components/Footer.jsx, src/components/RateUs.jsx
Hello Project Admin
I Added Rate Us Page - Solved #385 
Kindly Please go through this PR @singodiyashubham87 
https://github.com/singodiyashubham87/Draw-it-out/assets/161804629/a300a83e-67b5-47f3-aa4a-56984d25d187
=> Updated Rate Us Page

package-lock.json, src/App.jsx, src/components/DrawingShapes.jsx
*closes* #406 
This pull request introduces the drawing app's new brush functionalities and UI enhancements. The following brush types have been added:
-Rounded Brush: Applies a circular brush stroke with a rounded edge.
-Flat Brush: Applies a rectangular brush stroke with a flat edge.
-Watercolor Brush: Adds a semi-transparent watercolor effect to the strokes.
-Blur Brush: Strokes with a blur effect for a soft appearance.
The brush types have been implemented with basic functionality and can be further enhanced based on user feedback.
Testing was performed to ensure each brush type renders correctly and does not interfere with other drawing functionalities.
Example of how to mark a checkbox:-
-->
- [ x ] New feature (non-breaking change which adds …
=> feat: Adding the other strokes button for different types of brushes

src/components/Footer.jsx, src/components/FooterLink.jsx
*closes* #447
Hover effects on footer have been modified. Previously it was leading to a darker color on hovering the links in the footer but now it has been modified to look good.
=> Hover effects on footer made

package-lock.json, src/components/Footer.jsx, tailwind.config.js
*closes* #457
https://github.com/user-attachments/assets/f805e9dc-5fb0-444f-b836-d92717595cf9
=> Add hover effect to social media icons

src/index.css
*closes* #473 
- I have tested my changes via running it on my local system.
https://github.com/user-attachments/assets/66bbf259-fb5d-468f-832c-40c6c3211438
<hr>
_Please review and merge my pull-request under GSSoC'24_
=> Added minor transition effect.

src/components/Footer.jsx
*closes* #481 
fixed footer css
=> fixed footer in mobile view

src/components/Chatbot/Chatbot.jsx
*closes*  #476
The changes i made : 
1. fixes the chatbot popup container.
2. when user click outside the chatbot ,the chatbot bcm close and viceversa.
here is the screenrecording:
[screen-capture (8).webm](https://github.com/user-attachments/assets/d5a33210-2891-4536-a3b8-33246bb77990)
=> Fixes Issue No. : #476

src/components/Menu.jsx
*closes* #488
- I have made the changes and tested on my local machine.
Before
After
=> Fixed responsiveness issue of toolbar

src/components/DrawingShapes.jsx
=> fixed brush selector bug

package-lock.json, package.json, src/components/Home.jsx, src/components/Menu.jsx, src/components/Team/Contributor.jsx
=> Fixed the sizing for tablet screen size
